### PR TITLE
SecurityError: Failed to execute 'isSessionSupported' on 'XRSystem' when in iframe

### LINKED ISSUE #722: [BUG] - SecurityError: Failed to execute 'isSessionSupported' on 'XRSystem' when in iframe
**UE Version:**
UE5.6

**Frontend Version:**
E.g. UE5.5-1.2.4

**Problem component**
Frontend

**Description**
When loading pixel streaming in an iframe and you don't have the allow="xr-spatial-tracking" the dom will throw an Exception when trying to read the property .xr

SecurityError: Failed to execute 'isSessionSupported' on 'XRSystem': Access to the feature "xr" is disallowed by permissions policy.

**Steps to Reproduce:**
1. create an iframe an embed a pixel streaming app in it.

**Expected behavior**
We should wrap the navigator.xr.isSessionSupported() call in a try catch block so that we don't get an error if we are in an iframe.

### PR DESCRIPTION
**Pull request by leon**
fixes: #722

## Relevant components:
- [ ] Signalling server
- [ ] Common library
- [ ] Frontend library
- [x] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [ ] SFU

## Problem statement:
What problem does this PR address?
#722 

## Solution
How does this PR solve the problem?
Wraps the check in a try catch block and returns false if it throws

## Test Plan and Compatibility
What steps have you taken to ensure this PR maintains compataibility with the existing functionality? 
It only fixes a bug, does not introduce any changes to code paths.

### CODE REVIEW

File: Frontend/library/src/WebXR/WebXRController.ts [hunk 1]
```diff
@@ -485,12 +485,12 @@ export class WebXRController {
...
         }
 
-        if (navigator.xr) {
-            return navigator.xr.isSessionSupported(mode);
-        } else {
-            return new Promise<boolean>(() => {
-                return false;
-            });
-        }
+        try {
```
Comment (lukehb) [inline Frontend/library/src/WebXR/WebXRController.ts:490]: Adding a comment here to explain try-catch usage

```suggestion
        // Wrap in try-catch because access to XR object can be denied due
        // to browser security permissions (e.g. streaming from an iframe)
        try {
```

File: Frontend/library/src/WebXR/WebXRController.ts [hunk 2]
```diff
@@ -485,12 +485,12 @@ export class WebXRController {
...
+            if (navigator.xr) {
+                return navigator.xr.isSessionSupported(mode);
+            }
+        } catch {}
```
Comment (lukehb) [inline Frontend/library/src/WebXR/WebXRController.ts]: Our linter does not allow empty blocks, so I added resolve false to the catch block.

```suggestion
        } catch {
            return Promise.resolve(false);
        }
```

**Comment by leon** [comment]
Great!

It was such a simple fix, so forgot to run linting, will do that next time. 🤓
